#ifndef GLOBALS_H
#define GLOBALS_H

#define TOP_SCREEN_WIDTH  400
#define TOP_SCREEN_HEIGHT 240

#define BOTTOM_SCREEN_WIDTH  320
#define BOTTOM_SCREEN_HEIGHT 240

#define SQUARE_SIZE 20

#define TOP_BORDER 0
#define BOTTOM_BORDER (TOP_SCREEN_HEIGHT / SQUARE_SIZE - 1)
#define LEFT_BORDER 0
#define RIGHT_BORDER (TOP_SCREEN_WIDTH / SQUARE_SIZE - 1)

#define TOTAL_SQUARES (BOTTOM_BORDER - 1) * (RIGHT_BORDER - 1)

#endif